version: '3.8'


services:
 broker:
   image: bitnami/kafka:3.7
   container_name: broker
   environment:
     - KAFKA_CFG_NODE_ID=1
     - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
     - KAFKA_CFG_PROCESS_ROLES=controller,broker
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker:9093,2@broker2:9093
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
   ports:
     - "9092:9092"
     - "9101:9101"
   networks:
     - kraft-net


 broker2:
   image: bitnami/kafka:3.7
   container_name: broker2
   environment:
     - KAFKA_CFG_NODE_ID=2
     - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
     - KAFKA_CFG_PROCESS_ROLES=controller,broker
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker:9093,2@broker2:9093
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker2:9092
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
   ports:
     - "9093:9093"
     - "9102:9102"
   networks:
     - kraft-net


 schema-registry:
   image: confluentinc/cp-schema-registry:7.4.0
   container_name: schema-registry
   depends_on:
     - broker
     - broker2
   ports:
     - "8081:8081"
   environment:
     SCHEMA_REGISTRY_HOST_NAME: schema-registry
     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9092'
     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
   networks:
     - kraft-net


 connect:
   image: cnfldemos/cp-server-connect-datagen:0.5.3-7.1.0
   container_name: connect
   depends_on:
     - broker
   ports:
     - "8083:8083"
     - "28082:28082"
   environment:
     CONNECT_BOOTSTRAP_SERVERS: 'broker:9092'
     CONNECT_REST_ADVERTISED_HOST_NAME: connect
     CONNECT_REST_PORT: '28082'
     CONNECT_GROUP_ID: compose-connect-group
     CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
     CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
     CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
     CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
     CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
     CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
     CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.4.0.jar
     CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
     CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
     CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
     CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
   networks:
     - kraft-net


networks:
 kraft-net:
   driver: bridge
